name: Build Docker Image (Test Only)

on:
  push:
    branches-ignore:
      - "main"  # Exclude main branch
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"  # Tags like 0.0.1
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/workflows/**"

jobs:
  build-only:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch support)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Tag Version
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Build Docker Image (No Push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false  # Prevent pushing to registry
          load: false  # Avoid loading the image locally (useful for CI)
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}  
            ghcr.io/${{ github.repository }}:latest  
